name: Zig

on: [push]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build
      - run: zig build test
  test-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: brew install pkg-config pcre
      - run: zig build
      - run: zig build test
  test-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: vcpkg integrate install
      - run: vcpkg install pcre --triplet x64-windows-static
      - run: zig build
      - run: zig build test
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig fmt --check build.zig src/*.zig
